### ISSUE TITLE
Debug fails in a Windows 8.1 x64 / Visual Studio 2015 RC gulp environment

### ISSUE THREAD

**Issue by MarkStega** [sindresorhus/gulp-debug#14]
Running Gulp 3.8.11, gulp-debug 2.0.1, gulp-util-3.0.5

I am attempting to use a gulp pipe to debug in order to troubleshoot a gulp script.

When I added in .pipe(debug({title: 'Lint-ts:'})); the gulp script runner fails with

```
[11:53:00] TypeError: boolean is not a function
    at Gulp.gulp.task.gulp.src.pipe.debug.title (D:\Dropbox\Solutions\OHI\ASPDN-Aurelia-Skeleton\src\ASPDN_Aurelia_Skeleton\Gulpfile.js:35:21)
```

and no output from debug() is generated. I tried with and without a title. I also am using gulp-util.Log() with no issue.

I moved to modifying a know working script added the .pipe(debug... and that also causes the previously working script to fail.

**Comment by sindresorhus** [comment]
The error is coming from line 35 of your gulpfile. Without the full stack trace I can't help you more.

**Comment by MarkStega** [comment]
The full stacktrace is:

[14:01:17] Starting 'gen-ts-refs'...
[14:01:17] in gen-ts-defs1 ./wwwroot/typings/typescriptApp.d.ts
[14:01:17] in gen-ts-defs2 ./wwwroot/views/**/*.ts
[14:01:17] in gen-ts-defs3 [object Object]
[14:01:17] in gen-ts-defs4 [object Object]
[14:01:17] 'gen-ts-refs' errored after 6.98 ms[14:01:17] TypeError: boolean is not a function
    at Gulp.gulp.task.debug (d:\dropbox\solutions\ohi\aspdn-aurelia-skeleton\src\aspdn_aurelia_skeleton\gulpfile.js:36:21)
    at module.exports (d:\dropbox\solutions\ohi\aspdn-aurelia-skeleton\src\aspdn_aurelia_skeleton\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (d:\dropbox\solutions\ohi\aspdn-aurelia-skeleton\src\aspdn_aurelia_skeleton\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (d:\dropbox\solutions\ohi\aspdn-aurelia-skeleton\src\aspdn_aurelia_skeleton\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (d:\dropbox\solutions\ohi\aspdn-aurelia-skeleton\src\aspdn_aurelia_skeleton\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at d:\Dropbox\Solutions\OHI\ASPDN-Aurelia-Skeleton\src\ASPDN_Aurelia_Skeleton\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)
    at node.js:906:3
Process terminated with code 1.

The source is:

gulp.task('gen-ts-refs', function () {

    debug = true;
    if (debug)
    {
        gutil.log(gutil.colors.cyan('in gen-ts-defs1 ' + Config.appTypeScriptReferences));
        gutil.log(gutil.colors.cyan('in gen-ts-defs2 ' + [Config.allTypeScript]));
    }
    
    var target = gulp.src(Config.appTypeScriptReferences);
    var sources = gulp.src([Config.allTypeScript], { read: false });
    
    if (debug)
    {
        gutil.log(gutil.colors.cyan('in gen-ts-defs3 ' + target));
        gutil.log(gutil.colors.cyan('in gen-ts-defs4 ' + sources));
        target.pipe(debug({ title: 'gen-ts-defs4:', minimal: false })); <=== Error line
    }
    ...

**Comment by sindresorhus** [comment]
You have duplicate use of `debug`. Both as the gulp plugin and the boolean.

**Comment by MarkStega** [comment]
Thanks so much;

This environment (js) is so new to me that I am bound to make stupid mistakes like this one. 40 years of strongly typed languages, what can I say...

**Comment by sindresorhus** [comment]
If you had used ES6 `const` instead of `var` it would have been an error ;)

https://babeljs.io/

**Comment by MarkStega** [comment]
That's why I am heading as fast as I can to TypeScript; I agree that ES6 via Babel also would have been a good choice.
