### ISSUE TITLE
Error: Cannot find module 'through2'

### ISSUE THREAD

**Issue by aop** [sindresorhus/gulp-debug#6]
While trying to use this I get an error:

$ gulp

module.js:340
    throw err;
          ^
Error: Cannot find module 'through2'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/oskari/node_modules/gulp-debug/index.js:3:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)

**Comment by astroanu** [comment]
were you able to solve this ? i just installed with regular npm install, im on window btw.
